# This workflow will do a clean installation of node dependencies, then run our linter to show linting errors
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Lint Files
"on": push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
              npm ci
              npm run lint